// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2QJ7eQu_g_B0D7LYjz51iNsmEVsYT_lk',
    appId: '1:955657503714:web:37820c1021ad67cf8aefbb',
    messagingSenderId: '955657503714',
    projectId: 'fir-test-3d89d',
    authDomain: 'fir-test-3d89d.firebaseapp.com',
    storageBucket: 'fir-test-3d89d.firebasestorage.app',
    measurementId: 'G-1HN2LZPCM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_ob-EThn3cjyUJXk6-va0WPqjmdyONY',
    appId: '1:955657503714:android:b05c0c86f7f315688aefbb',
    messagingSenderId: '955657503714',
    projectId: 'fir-test-3d89d',
    storageBucket: 'fir-test-3d89d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SL0t_uEmuoQv9iDliuLYNG6kIKHguS0',
    appId: '1:955657503714:ios:46fa01ac57874ce18aefbb',
    messagingSenderId: '955657503714',
    projectId: 'fir-test-3d89d',
    storageBucket: 'fir-test-3d89d.firebasestorage.app',
    iosBundleId: 'com.example.quickstartFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5SL0t_uEmuoQv9iDliuLYNG6kIKHguS0',
    appId: '1:955657503714:ios:46fa01ac57874ce18aefbb',
    messagingSenderId: '955657503714',
    projectId: 'fir-test-3d89d',
    storageBucket: 'fir-test-3d89d.firebasestorage.app',
    iosBundleId: 'com.example.quickstartFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2QJ7eQu_g_B0D7LYjz51iNsmEVsYT_lk',
    appId: '1:955657503714:web:be677b6a3eaa471f8aefbb',
    messagingSenderId: '955657503714',
    projectId: 'fir-test-3d89d',
    authDomain: 'fir-test-3d89d.firebaseapp.com',
    storageBucket: 'fir-test-3d89d.firebasestorage.app',
    measurementId: 'G-SWVQ3QQHST',
  );
}
